Uploading everything
stepancar-web-programming/2023-fall-lab-portfolio-amiri-z.-f. pull request #1
Opened 2024-01-04 16:04 UTC by amirymax

2024-01-07 06:29 UTC, stepancar commented on css/style.css
> +    /* display: flex; */
пожалуйста, приготовьте ПР к ревью. убелидитесь что в нем нет ничего лишнего

2024-01-07 06:30 UTC, stepancar commented on index.html
> +    <script src="js/jquery.min.js"></script>
Более производительно воспользоваться существующими cdn сервисами, давайте сделаем это

2024-01-07 06:32 UTC, stepancar commented on js/script.js
> +    $('#video-section').html('<p><b>The best goal ever! It was better than everything!</b></p>  <iframe width="560" height="315" src="https://www.youtube.com/embed/ZC_XihZGPEg?si=KAz7HItciZuP2wU3" ti
Для такого маленького функционала импорт целого jquery кажется неразумным, если на это не вестких причин - предлагаю его удалить и сделать все на vanila js

2024-01-07 06:33 UTC, stepancar requested changes
Сайт выглядит плохо на узких экранах, так как у вас довольно простая визитка, на защиту прошу разобраться в тома как делать верстку responsive и исправить

2024-02-26 09:56 UTC, stepancar commented on js/script.js
> +}
Код не форматирован. Это говорит о том что в проекте не настроены линтеры/форматтеры. Пожалуйста добавьте автоматизацию

2024-02-26 09:57 UTC, stepancar requested changes
Не хватает автоматизации проверки кода

2024-03-14 16:26 UTC, amirymax commented
Линтер добавлен и код отформатирован

2024-03-14 16:26 UTC, stepancar commented on node_modules/.bin/acorn
В репозиторий закоммичены node_modules

2024-03-14 16:27 UTC, amirymax commented on node_modules/.bin/acorn
Их надо убрать?

2024-03-14 16:29 UTC, stepancar requested changes
Перед отправкой ПР на ревью - хорошая практика, провести ревью своих изменений самому. Все ли изменения все еще имеют смысл? Все ли TODO вы сделали?  Если вы откроете ваш ПР - вы заметите что интерфейс тормозит. Это связано с объемом файлов , которые вы закоммитили. Дальше должен появиться вопрос, откуда столько файлов.  Пожалуйста, проводите минимальный чек ап, прежде чем звать на ревью человека.

2024-03-14 16:30 UTC, stepancar commented on node_modules/.bin/acorn
Как вы думаете? Если ваш проект использует 1000000 пакетов - должен ли миллион этих пакетов храниться в вашем репозитории?

2024-03-14 16:33 UTC, amirymax commented on node_modules/.bin/acorn
Хорошо, я вас понял. Убрал лишние файлы (насколько я знаю)

2024-03-14 16:58 UTC, stepancar commented on css/style.css
> +}
По этому фрагменту кода видно что не использовалось форматирование автоматикой.

2024-03-14 17:14 UTC, stepancar commented on package.json
> +  "scripts": {
Вижу конфиг eslint в проекте, но не вижу скрипт для запуска eslint, не вижу интеграции с github actions или любым другим CI.

2024-03-14 17:16 UTC, stepancar commented
node_modules удалены, но причина по которой он пакеты попали в репозиторий не устранена.

2024-03-14 17:18 UTC, stepancar commented on js/script.js
> +  });
по этому фрагменту кода видно что нет валидации форматирования

2024-03-14 17:20 UTC, stepancar commented on index.html
> +    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
эта версия jquery https://blog.jquery.com/2021/03/02/jquery-3-6-0-released/
2021 года. По какой причине используется не новая версия?

2024-03-14 17:21 UTC, stepancar commented on index.html
> +    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
Для какой задачи в проекте используется jquery?

2024-03-14 17:22 UTC, stepancar commented on package.json
> +  "main": "index.js",
файла по такому пути не существует.

2024-03-14 17:24 UTC, stepancar commented on package.json
> +  "name": "2023-fall-lab-portfolio-amiri-z.-f",
Вероятно вы бы хотели избежать паблишинга вашего приложения в npm, тогда следует воспользоваться https://docs.npmjs.com/cli/v10/configuring-npm/package-json#private

2024-03-14 17:27 UTC, stepancar commented on about.html
> +      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
этот релиз появился 2 года назад. По какой причине в новом проекте не используется новая версия?

2024-03-15 06:33 UTC, stepancar requested changes
В рамка этого коммита https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-amiri-z.-f./pull/1/commits/73a7522a04248121f47b1e557c556d94f7424e9a#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051
вы внесли изменение в index.html
Однако валидируя демо по приложенной ссылке https://amirymax.github.io/2023-fall-lab-portfolio-amiri-z.-f./
 заметил, что этих изменений там нет.
 Получается я делаю ревью одного кода, а валидирую результат работы другого кода.
На лицо недоработка в автоматизации в проекте. Пожалуйста, исправьте эту проблему

2024-03-15 23:58 UTC, amirymax commented
Изменения в html файлы были введены потому, что я оттуда удалил jquery, который уже нигде не использовался. Также были проблемы с github pages и я еще долго исправлял , чтобы страницы отображались. 
Автоматизацию насколько я понимаю, выполнил для всех файлов html, css, js. Разве что могут быть ошибки, которых я мог сам не понимать. Например вчера github actions при запуске автоматизации проверки давал ошибку, я пытался исправить, но не получилось. А сегодня там все выполняется до конца. 
Поэтому, если есть ошибки, готов узнать о них и исправлять.

2024-03-16 18:19 UTC, stepancar commented on package.json
> +    "eslint-config-standard": "^17.1.0"
У нас есть отдельный вопрос в рубежной работе про разницу devDependencies и dependencies

2024-03-16 18:22 UTC, stepancar commented on about.html
> +    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
Устаревшая версия jquery. По какой причине в свежей лабораторной работе используется она?

2024-03-16 18:23 UTC, stepancar requested changes
не все комментарии разрезолвлены

2024-03-16 18:31 UTC, amirymax commented on package.json
> +    "eslint-config-standard": "^17.1.0"
извиняюсь за такую тупую ошибку, я просто делал с помощью npm --save-dev и не особо проверил файл package.json

2024-03-16 18:40 UTC, stepancar requested changes
В этом коммите вы сделали удлаение jquery
https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-amiri-z.-f./pull/1/commits/6d975b264b65691c54f11a94543513a4e9b1308b
Однако во время ревью я заметил что на демо стэнде он все так же присутствует.
Это значит что автоматизации деплоя нет. Это приводит к запутанности процесса ревью, так как ревьюер смотрит в один код, а на демо стэнде другой код.
<img width="1721" alt="Screenshot 2024-03-16 at 11 37 29 AM" src="https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-amiri-z.-f./assets/2854910/5f2df90e-c553-48ba-af8d-a14ddb92436d">

2024-03-16 18:43 UTC, amirymax commented
Просто я еще не успел сделать форк и запустить на github pages со своего профиля.

2024-03-17 23:02 UTC, stepancar commented
> Просто я еще не успел сделать форк и запустить на github pages со своего профиля.

Проблема ведь в том, что вы делаете это вручную.

2024-03-17 23:04 UTC, stepancar approved these changes
Лабораторная работа зачтена

2024-03-17 23:10 UTC, merged